### ISSUE TITLE
Cannot run tests using --interp

### ISSUE THREAD

**Issue by boronine** [husl-colors/husl-haxe#3]
Using Haxe version 3.2.1

```
herbie:husl-haxe alexei$ haxe -cp src -cp test -main RunTests --interp
Class: ColorConverterTest E
* ColorConverterTest::testHusl()
ERR: exception thrown : Invalid field access : __s

Called from /usr/local/lib/haxe/std/haxe/format/JsonParser.hx line 56
Called from test/ColorConverterTest.hx line 80
Called from <builtin> line 1
Called from /usr/local/lib/haxe/std/neko/_std/Reflect.hx line 58
Called from /usr/local/lib/haxe/std/haxe/unit/TestRunner.hx line 115


FAILED 1 tests, 1 failed, 0 success
```

**Comment by boronine** [comment]
Looks like it was missing `-resource test/resources/snapshot-rev4.json@snapshot-rev4`. Can you amend the README? This should be considered the primary testing command, since it doesn't require anything other than Haxe to run. Few people are going to have all the other targets installed in order to run `tests.hxml`.

**Comment by Eiyeron** [comment]
Indeed, I forgot this part of the command line, my bad.

**Comment by boronine** [comment]
Looks like it's fixed!
