### ISSUE TITLE
README needs API documentation

### ISSUE THREAD

**Issue by boronine** [husl-colors/husl-haxe#4]
Template: https://github.com/husl-colors/husl/blob/master/README.md

**Comment by Eiyeron** [comment]
Haxe has an official way to create documentation : [dox](https://github.com/HaxeFoundation/dox). I'm currently documenting the source code to make the generated documentation useable. Would you prefer using Dox or keep the documentation in the readme?

**Comment by boronine** [comment]
The problem with auto-generated documentation is hosting. If we want to host it on husl-colors.org we need to integrate that into our build and deploy process. Since the public API is only 8 functions I don't think it's worth it. However, (!) it would be great to have this code well-documented. I'm currently looking at the JavaScript output and it's looking good. I think we can make this the reference implementation.

**Comment by Eiyeron** [comment]
Do you happen to know the value ranges for the different color systems in husl-java? I lack LCH's C* range for the documentation. It'll probably look like this
![screenshot from 2016-11-20 17-50-20](https://cloud.githubusercontent.com/assets/936086/20464101/81a47f68-af41-11e6-8167-3c35c1757085.png)

**Comment by boronine** [comment]
That looks really nice! The C in LCH is does not have a well-defined upper bound, it's different for every L and H, hence `maxChromaForLH`. You could write "C: [0; ?] Upper bound varies depending on L and H"

**Comment by Eiyeron** [comment]
Thanks, pushed the new documentation to master. If you want to make some critiques about the changes, please do so it can be improved.
