### ISSUE TITLE
tests.hxml: tests don't run unless target previously compiled

### ISSUE THREAD

**Issue by boronine** [husl-colors/husl-haxe#6]
Using JavaScript as an example.

```
herbie:husl-haxe alexei$ rm -rf bin
herbie:husl-haxe alexei$ haxe tests.hxml 
Target: JS
module.js:327
    throw err;
    ^

Error: Cannot find module '/Users/alexei/HUSL/husl-haxe/bin/js/Main.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
Error: Command failed with error 1
herbie:husl-haxe alexei$ ls bin
ls: bin: No such file or directory
```

However, if I pre-compile it works:

```
herbie:husl-haxe alexei$ haxe -main RunTests -cp src  -cp test -resource test/resources/snapshot-rev4.json@snapshot-rev4 -js bin/js/Main.js
herbie:husl-haxe alexei$ haxe tests.hxml 
Target: JS
Class: ColorConverterTest .

OK 1 tests, 0 failed, 1 success
```

**Comment by Eiyeron** [comment]
Alas, that's the issue of the current way to test the languages. I'll offer instead a suite of small build files to be able to cherry-pick what to build.

**Comment by boronine** [comment]
Hmm... I agree with the idea of splitting up testing, but separate hxml files is a bit too much. I think the best course of action is to just list all the testing commands in the README as you're doing already for Java and C++. Easy for us and easy for people unfamiliar with hxml.

**Comment by Eiyeron** [comment]
I haven't tested the windows test commands nor can do the Mac ones but as `test.hxml` has been removed, the issue has no reason to stay open anymore.
