### ISSUE TITLE
Concerns about functions

### ISSUE THREAD

**Issue by Eiyeron** [husl-colors/husl-haxe#8]
I have one last concern about the codebase : should we remove husl-java's XYZ/LUV/LCH related functions? The canonical implementation doesn't implement them and they're coming from husl-java, so should we remove them?

**Comment by boronine** [comment]
I just did a quick scan over the code, not sure which functions you mean? (As far as I'm concerned, the public API is 8 functions (HUSL, HUSLp <-> RGB, hex)).

**Comment by Eiyeron** [comment]
Those ones : 
```haxe
xyzToRgb(tuple:Array<Float>)
rgbToXyz(tuple:Array<Float>)
xyzToLuv(tuple:Array<Float>)
luvToXyz(tuple:Array<Float>)
luvToLch(tuple:Array<Float>)
lchToLuv(tuple:Array<Float>)
huslToLch(tuple:Array<Float>)
lchToHusl(tuple:Array<Float>)
huslpToLch(tuple:Array<Float>)
lchToHuslp(tuple:Array<Float>)
lchToRgb(tuple:Array<Float>)
rgbToLch(tuple:Array<Float>)
```

Those were public in the Java lib and thus are also public here too.

**Comment by boronine** [comment]
Ah, I see, you mean make them private? Yes, I think it would be preferable.

**Comment by Eiyeron** [comment]
I would have thought of removing them because most of them aren't used anywhere else, they could overlap the work of other libraries (eventually, keeping functions like `huslToLch` would be interesting to avoid precision loss by using intermediate functions) and add more work to support.

**Comment by boronine** [comment]
I agree with that reasoning. There seem to exist some libraries for Haxe already which are concerned with color conversions. I think a small and simple public API is a win for HUSL.

**Comment by Eiyeron** [comment]
Ok, I'll work in removing those functions.

```
xyzToRgb
rgbToXyz
xyzToLuv
luvToXyz
luvToLch
lchToLuv
lchToRgb
rgbToLch
```

Concerning the previously listed `xxxTohusl(p)` and `husl(p)ToXXX`, I'd like to know what to do with them. They don't belong in the original API but they could eventually be useful in specific cases.

**Comment by boronine** [comment]
To be clear, we are talking about making them private, right? I think they should all be private to make things simple.

**Comment by boronine** [comment]
You can push changes to haxe-wip branch here: https://github.com/husl-colors/husl/tree/haxe-wip/haxe I'm making changes to the build, but the code will live in the `/haxe` subdirectory. I'll delete this repo later.

**Comment by Eiyeron** [comment]
I wondered about actually removing them from the code (as in deleting them) but actually, looks like they're used in rgb/lch ←→ husl.

Also, okay for the repo change. I'm going to switch over this one.

**Comment by Eiyeron** [comment]
I had to kep them so I made them private and overrode their privacy in the test unit to keep it passing. The change is only done on husl repo, not here.

**Comment by boronine** [comment]
👍 deleting this repo. Progress: https://github.com/husl-colors/husl/issues/29
